create table usuario (
  user_ref uuid not null,
  
  nome text not null,
  tipo text not null,
  email text not null,
  telefone text not null,
  saldo_inicial numeric(15, 2) not null,
  
  constraint usuario_pkey primary key (user_ref),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint usuario_user_ref_fkey foreign KEY (user_ref) references auth.users (id)
);

create table categorias (
  id bigint primary key generated always as identity,
  nome text not null,
  descricao text not null,
  
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.transacoes (
  id bigint generated by default as identity not null,
  data date not null,
  descricao text null,
  valor numeric(15, 2) not null,
  tipo text not null,
  status text not null,
  categoria_id bigint null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid null,
  constraint transacoes_pkey primary key (id),
  updated_at timestamp with time zone not null default now(),
  constraint transacoes_categoria_id_fkey foreign KEY (categoria_id) references categorias (id),
  constraint transacoes_user_id_fkey foreign KEY (user_id) references auth.users (id),
  constraint transacoes_status_check check (
    (
      status = any (
        array['Aguardando'::text, 'Pago'::text, 'Vencida'::text]
      )
    )
  ),
  constraint transacoes_tipo_check check (
    (
      tipo = any (array['Entrada'::text, 'Saída'::text])
    )
  )
) TABLESPACE pg_default;

create table lancamento_usuario_futuras (
  id bigint primary key generated always as identity,
  data_prevista date not null,
  valor numeric(15, 2) not null,
  tipo text check (tipo in ('entrada', 'saida')) not null,
  conta_id bigint references usuario (id),
  descricao text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);
